import { describe, expect, it, vi } from 'vitest'
import { FileOpenRequests } from './file-open-requests'

describe('系统文件打开请求', () => {
  it('冷启动先缓存，窗口创建后仍等待渲染监听就绪，且只投递一次', () => {
    const requests = new FileOpenRequests()
    const wake = vi.fn()
    const deliver = vi.fn()
    requests.request('/视频/第一集.mkv')
    requests.setWindowOpener(wake)
    expect(wake).toHaveBeenCalledOnce()
    expect(deliver).not.toHaveBeenCalled()
    requests.rendererReady(deliver)
    requests.rendererReady(deliver)
    expect(deliver).toHaveBeenCalledExactlyOnceWith('/视频/第一集.mkv')
  })

  it('启动过程中连续打开保留最新意图，运行中可以再次打开同一文件', () => {
    const requests = new FileOpenRequests()
    const deliver = vi.fn()
    requests.request('/first.mp4')
    requests.request('/last.mkv')
    requests.rendererReady(deliver)
    expect(deliver).toHaveBeenCalledExactlyOnceWith('/last.mkv')
    requests.request('/last.mkv')
    expect(deliver).toHaveBeenCalledTimes(2)
  })

  it('窗口关闭或重载后不向旧页面投递，新页面就绪后继续打开', () => {
    const requests = new FileOpenRequests()
    const oldPage = vi.fn()
    const newPage = vi.fn()
    requests.rendererReady(oldPage)
    requests.rendererUnavailable()
    requests.setWindowOpener(vi.fn())
    requests.request('/next.mkv')
    expect(oldPage).not.toHaveBeenCalled()
    requests.rendererReady(newPage)
    expect(newPage).toHaveBeenCalledExactlyOnceWith('/next.mkv')
  })

  it('唤醒过程若重建窗口，必须等待新窗口就绪', () => {
    const requests = new FileOpenRequests()
    const oldPage = vi.fn()
    requests.rendererReady(oldPage)
    requests.setWindowOpener(() => requests.rendererUnavailable())
    requests.request('/next.mp4')
    expect(oldPage).not.toHaveBeenCalled()
    const newPage = vi.fn()
    requests.rendererReady(newPage)
    expect(newPage).toHaveBeenCalledExactlyOnceWith('/next.mp4')
  })

  it('windows 启动参数和二次启动共用入口，忽略非视频参数', () => {
    const requests = new FileOpenRequests()
    const deliver = vi.fn()
    const wake = vi.fn()
    requests.setWindowOpener(wake)
    requests.rendererReady(deliver)
    requests.requestFromArgv(['Marchen.exe', '--flag'])
    expect(wake).not.toHaveBeenCalled()
    requests.requestFromArgv(['Marchen.exe', 'C:\\Anime\\EP01.MKV'])
    expect(deliver).toHaveBeenCalledExactlyOnceWith('C:\\Anime\\EP01.MKV')
  })
})

describe('种子文件打开队列', () => {
  it('多文件按序消费，重复路径不插入，取消后继续下一个', () => {
    const requests = new FileOpenRequests()
    const deliver = vi.fn()
    requests.requestFromArgv(['Marchen', '/one.torrent', '/two.torrent', '/one.torrent'])
    requests.torrentReady(deliver)
    expect(deliver).toHaveBeenCalledTimes(1)
    expect(deliver.mock.calls[0][0].path).toBe('/one.torrent')
    requests.torrentHandled('wrong-id')
    expect(deliver).toHaveBeenCalledTimes(1)
    requests.torrentHandled(deliver.mock.calls[0][0].id)
    expect(deliver.mock.calls[1][0].path).toBe('/two.torrent')
  })
  it('窗口重载重发未确认种子，不重放已消费视频', () => {
    const requests = new FileOpenRequests()
    const deliver = vi.fn()
    requests.request('/one.torrent')
    requests.torrentReady(deliver)
    requests.rendererUnavailable()
    requests.torrentReady(deliver)
    expect(deliver.mock.calls[0][0].id).toBe(deliver.mock.calls[1][0].id)
    requests.torrentHandled(deliver.mock.calls[1][0].id)
    requests.rendererUnavailable()
    requests.torrentReady(deliver)
    expect(deliver).toHaveBeenCalledTimes(2)
  })
})
